ALTER USER sys IDENTIFIED BY password;

ALTER SESSION SET CONTAINER = orclpdb1;

CREATE USER javaproject_2523 IDENTIFIED BY password;

GRANT CREATE SESSION TO javaproject_2523;

GRANT CREATE TABLE TO javaproject_2523;

ALTER USER javaproject_2523 QUOTA UNLIMITED ON USERS;

